### ISSUE TITLE
WoT 1.1 Support

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/wot-td#45]
Here a list of what is missing:

- [x] #47
- [x] #53
- [x] #46
- [x] #59
- [x] #56
- [x] #58
- [x] #63
- [x] #62
- [x] #71
- [x] #73
- [x] #75
- [ ] #77
- [x] #78
- [x] ~#80~

**Comment by dodomorandi** [comment]
There are two parts in the spec noted as "at risk":

* Table of [data schema vocabulary definitions](https://www.w3.org/TR/wot-thing-description11/#sec-data-schema-vocabulary-definition)
* [Combo security scheme](https://www.w3.org/TR/wot-thing-description11/#combosecurityscheme)

The former should not be a problem for us, but the second it is. Can we try to get some information about we should expect?

**Comment by dodomorandi** [comment]
`Form::op` must be validated against a specific subset of operations depending on the context:

* [PropertyAffordance](https://www.w3.org/TR/wot-thing-description11/#propertyaffordance) requires that `op` must be `readproperty`, `writeproperty`, `observeproperty`, `unobserveproperty` or an array of one or more of these;
* [ActionAffordance](https://www.w3.org/TR/wot-thing-description11/#actionaffordance) requires that `op` must be `invokeaction`, `queryaction`, `cancelaction` or an array of one or more of these;
* [EventAffordance](https://www.w3.org/TR/wot-thing-description11/#eventaffordance) requires that `op` must be `subscribeevent`, `unsubscribeevent` or an array with both.

At this point, it seems that each different type of affordance uses a different subset of possible operations. This aspect should be thoroughly checked in order to consider splitting the `Operation` enum in separated enums and keep these check at compile time as much as possible.

**Comment by dodomorandi** [comment]
There is a harder constrain related to [MultiLanguage](https://www.w3.org/TR/wot-thing-description11/#multilanguage), which requires that each name must be a valid language tag as defined in [BCP47](https://www.w3.org/TR/wot-thing-description11/#bib-bcp47).

**Comment by dodomorandi** [comment]
`DataSchema` does not include the `default` field.

**Comment by dodomorandi** [comment]
`NumberSchema` and `IntegerSchema` are missing:

* `exclusiveMinimum`
* `exclusiveMaximum`

I see an issue with this, because it is possible to specify a combination of conflicting `minimum`/`exclusiveMinimum` and `maximum`/`exclusiveMaximum`. We should consider the hypothesis of restricting the possible combinations.

**Comment by dodomorandi** [comment]
`StringSchema` is missing:

* `minLength`
* `pattern`
* `contentEncoding`
* `contentMediaType`

**Comment by dodomorandi** [comment]
We currently do not support extending `SecuritySchema`, but once we start implementing the support, we must keep in mind the following:

> The value assigned to the name scheme MUST be defined within a [Vocabulary](https://www.w3.org/TR/wot-thing-description11/#dfn-vocab-term) included in the [Thing Description](https://www.w3.org/TR/wot-thing-description11/#dfn-thing-description), either in the standard [Vocabulary](https://www.w3.org/TR/wot-thing-description11/#dfn-vocab-term) defined in [§ 5. TD Information Model](https://www.w3.org/TR/wot-thing-description11/#sec-vocabulary-definition) or in a [TD Context Extension](https://www.w3.org/TR/wot-thing-description11/#dfn-context-ext).

Therefore we need to support extending the basic _security schemes_ without being to lax. Moreover, we need to implement specific support for `in` field, which has a very specific grammar.

Last but not least:
> The names of URI variables declared in a SecurityScheme MUST be distinct from all other URI variables declared in the TD.

**Comment by dodomorandi** [comment]
[Link](https://www.w3.org/TR/wot-thing-description11/#link) is missing:

* `sizes`
* `hreflang`

There is an additional _best practice relation type table_, but I am unsure of how we should use it (being a recommendation is not something mandatory, but on the other hand maybe we should support helper methods to follow these recommendations?).

**Comment by dodomorandi** [comment]
`Form::op` is missing the following variants:

* `queryaction`
* `cancelaction`
* `observeallproperties`
* `unobserveallproperties`
* `subscribeallevents`
* `unsubscribeallevents`
* `queryallactions`

**Comment by lu-zero** [comment]
Stricter validation was not deemed problematic to be a showstopper.
